[package]
name = "tahini_tarpc"
version = "0.1.0"
edition = "2021"


[lib]
name="tahini_tarpc"
path="src/lib.rs"

[dependencies]
erased-serde = "0.4.6"
serde = { version = "1.0.219", features = ["derive", "serde_derive"] }
serde_json = { version = "1.0.141", features = ["preserve_order"] }
# tokio = { version = "1.46.1", features = ["io-std", "io-util", "rt", "mio", "libc", "tokio-macros", "macros", "rt-multi-thread"] }
# tokio = { version = "1.42.0", features = ["io-std", "io-util", "rt", "mio", "libc"] }

alohomora = {version = "0.1.0", git = "https://github.com/brownsys/Sesame", branch = "extensions_devel"}
tahini_tarpc_derive ={version = "0.1.0", git = "https://github.com/alex-douk/tahini_lib", branch = "standalone_tahini", optional = true}
hoodini_core =   {version="0.1.0", git = "https://github.com/alex-douk/tahini_lib", branch = "standalone_tahini", features=["attest"]}
hoodini_client = {version="0.1.0", git = "https://github.com/alex-douk/tahini_lib", branch = "standalone_tahini"}
hoodini_server = {version="0.1.0", git = "https://github.com/alex-douk/tahini_lib", branch = "standalone_tahini"}
# async-trait = "0.1.83"
tarpc = { version = "0.34.0", features = ["full"]}
pin-project-lite = "0.2.14"
aws-lc-rs = "1.13.1"
futures = "0.3.31"
tokio-util = "0.7.16"
tokio-serde = { version = "0.9.0", features = ["json", "serde_json"] }
tokio = "1.47.1"


[patch.crates-io]
funty = { git = "https://github.com/bitvecto-rs/funty/", rev = "7ef0d890fbcd8b3def1635ac1a877fc298488446" }

[features]
derive = ["dep:tahini_tarpc_derive"]


[dependencies.url]
version = "=2.5.0"

[dependencies.icu_properties_data]
version = "=1.5.1"

[dependencies.pest]
version="=2.8.0"

[dependencies.pest_meta]
version="=2.8.0"

[dependencies.pest_generator]
version="=2.8.0"

[dependencies.native-tls]
version="=0.2.11"
